server:
  port: 8083
  undertow:
    threads:
      worker: 256
      io: 8

spring:
  application:
    name: fib-product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fib_product?useUnicode=true&characterEncoding=utf8&connectTimeout=5000&socketTimeout=30000&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: fangyh102034
    type: com.alibaba.druid.pool.DruidDataSource