server:
  port: 8085
  undertow:
    threads:
      worker: 256
      io: 8

spring:
  application:
    name: fib-mall
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fib_mall?useUnicode=true&characterEncoding=utf8&connectTimeout=5000&socketTimeout=30000&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: fangyh102034
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8843
        username: nacos
        password: nacos
      config:
        server-addr: 127.0.0.1:8843
        file-extension: yml
        refresh-enabled: true
        username: nacos
        password: nacos
    inetutils:      
      preferred-networks:  
      - 192.168
  config:
    import:
    - optional:nacos:${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
     
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations:
      - classpath:sql/schema-mysql.sql
      data-locations:
      - classpath:sql/data-mysql.sql
   
seata:
  enabled: true
  tx-service-group: seata_tx_group
  service:
    vgroup-mapping:
      seata_tx_group: default
      grouplist:
        default: 127.0.0.1:8091
  data-source-proxy-mode: AT
  registry:
    type: nacos
    nacos:
     server-addr: 127.0.0.1:8843,127.0.0.1:8845,127.0.0.1:8847
     group: SEATA_GROUP
     username: nacos
     password: nacos
  enable-auto-data-source-proxy: true

logging:
  config: classpath:config/log/logback.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:**/mapper/*.xml